Repository syncromatics/kafmesh, pull requests merged in 2020-03, with the labels that each got.

#11 (+semver: fix) Fix time package import checks
  pkg/generator/serviceTemplate.go
Labels: bug

#12 (+semver: fix) Fully qualify sink consumer group name
  pkg/generator/gen.go
  pkg/generator/sinkTemplate.go
  pkg/generator/sinkTemplate_test.go
Labels: bug

#13 (+semver: fix) Synchronizers should create compact topics
  pkg/generator/topicTemplate.go
Labels: bug

#14 (+semver: feature) Add context.Context to synchronizer and implement …
  pkg/generator/synchronizerTemplate.go
  pkg/generator/synchronizerTemplate_test.go
Labels: enhancement

#15 (+semver: feature) Abstract more of synchronizer
  go.mod
  go.sum
  makefile
  pkg/generator/gen_test.go
  pkg/generator/synchronizerTemplate.go
  pkg/generator/synchronizerTemplate_test.go
  pkg/generator/topicTemplate.go
  pkg/generator/topicTemplate_test.go
  pkg/runner/protoSynchronizer.go
Labels: bug, enhancement

#16 Add view source and sink
  pkg/generator/emitterTemplate.go
  pkg/generator/gen.go
  pkg/generator/gen_test.go
  pkg/generator/serviceTemplate.go
  pkg/generator/serviceTemplate_test.go
  pkg/generator/sourceTemplate.go
  pkg/generator/sourceTemplate_test.go
  pkg/generator/topicTemplate.go
  pkg/generator/viewSinkTemplate.go
  pkg/generator/viewSinkTemplate_test.go
  pkg/generator/viewSourceTemplate.go
  pkg/generator/viewSourceTemplate_test.go
  pkg/models/component.go
  pkg/models/component_test.go
  pkg/runner/protoSynchronizer.go
Labels: enhancement
